name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Build backend
        run: mvn clean package
      - name: Run backend tests
        run: mvn test

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install Chromium
        run: |
          sudo apt-get update
          wget http://ftp.ru.debian.org/debian/pool/main/c/chromium/chromium_136.0.7103.113-1_amd64.deb
          sudo dpkg -i chromium_136.0.7103.113-1_amd64.deb || sudo apt-get -f install -y
          echo "CHROME_BIN=/usr/bin/chromium" >> $GITHUB_ENV
      - name: Debug Chromium version
        run: chromium --version
      - name: Install dependencies
        run: npm ci
      - name: Install Protractor
        run: npm install -g protractor
      - name: Install ChromeDriver
        run: |
          sudo cp /usr/lib/chromium/chromedriver node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_136.0.7103.113
          sudo chmod +x node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_136.0.7103.113
      - name: Debug Chromium and ChromeDriver
        run: |
          chromium --version
          node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_136.0.7103.113 --version || echo "ChromeDriver not found"
      - name: Debug WebDriver
        run: ls -la node_modules/protractor/node_modules/webdriver-manager/selenium
      - name: List test files
        run: |
          echo "Unit test files:"
          find src/app -name "*.spec.ts"
          echo "E2E test files:"
          find e2e/src -name "*.e2e-spec.ts"
      - name: Debug Karma and Chromium
        run: |
          npx karma --version
          chromium --version
          npx ng version
          protractor --version
      - name: Build project
        run: npx ng build
      - name: Run unit tests
        run: npx ng test --browsers=ChromiumHeadless --watch=false
        env:
          CHROME_BIN: /usr/bin/chromium
      - name: Kill existing processes on port 7860
        run: |
          fuser -k 7860/tcp || true
      - name: Kill existing processes on port 8080
        run: |
          fuser -k 8080/tcp || true
      - name: Start backend
        run: |
          cd ../backend
          mvn spring-boot:run &
          sleep 10
      - name: Debug backend port
        run: lsof -i :8080 || echo "Port 8080 is free"
      - name: Start server for E2E tests
        run: |
          npx ng serve --port 7860 --proxy-config proxy-conf.json &
          echo "E2E_BASE_URL=http://localhost:7860/" >> $GITHUB_ENV
        env:
          CI: true
      - name: Wait for server
        run: sleep 10
      - name: Run E2E tests
        run: npx ng e2e
        env:
          CHROME_BIN: /usr/bin/chromium
      - name: Check test results
        if: always()
        run: |
          echo "Test results summary:"
          if [ -d "coverage" ]; then
            echo "Coverage report generated. Listing files:"
            ls -la coverage
            if [ -f "coverage/lcov.info" ]; then
              echo "Coverage summary:"
              cat coverage/lcov.info | grep -E '^(SF|LF|LH)' || echo "No coverage data"
            fi
          else
            echo "No coverage report generated."
          fi
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: frontend/coverage
          retention-days: 7
