name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build backend
        run: mvn clean package

      - name: Run backend tests
        run: mvn test

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Remove google-chrome-stable
        run: |
          sudo apt-get remove -y google-chrome-stable || true
          sudo apt-get autoremove -y

      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libgbm1 libu2f-udev

      - name: Install Chromium and ChromeDriver
        run: |
          wget http://ftp.ru.debian.org/debian/pool/main/c/chromium/chromium_136.0.7103.113-1_amd64.deb
          wget http://ftp.ru.debian.org/debian/pool/main/c/chromium/chromium-driver_136.0.7103.113-1_amd64.deb
          sudo dpkg -i chromium_136.0.7103.113-1_amd64.deb || sudo apt-get -f install -y
          sudo dpkg -i chromium-driver_136.0.7103.113-1_amd64.deb || sudo apt-get -f install -y
          echo "CHROME_BIN=/usr/bin/chromium" >> $GITHUB_ENV

      - name: Debug Chromium install
        run: |
          chromium --version || echo "Chromium not found"
          /usr/lib/chromium-browser/chromedriver --version || echo "ChromeDriver not found"

      - name: Install dependencies
        run: npm ci

      - name: Install Protractor
        run: npm install -g protractor

      - name: Copy ChromeDriver to WebDriver Manager
        run: |
          mkdir -p node_modules/protractor/node_modules/webdriver-manager/selenium
          sudo cp /usr/lib/chromium-browser/chromedriver node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_136.0.7103.113
          sudo chmod +x node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_136.0.7103.113

      - name: Debug WebDriver
        run: |
          chromium --version || echo "Chromium not found"
          node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_136.0.7103.113 --version || echo "ChromeDriver not found"
          ls -la node_modules/protractor/node_modules/webdriver-manager/selenium

      - name: Build project
        run: npx ng build

      - name: Run unit tests
        run: npx ng test --browsers=ChromiumHeadless --watch=false --no-sandbox
        env:
          CHROME_BIN: /usr/bin/chromium

      - name: Kill existing processes
        run: |
          fuser -k 7860/tcp || true
          fuser -k 8080/tcp || true

      - name: Start backend
        run: |
          cd ../backend
          mvn spring-boot:run &
          sleep 10

      - name: Start Angular server for E2E
        run: |
          npx ng serve --port 7860 --proxy-config proxy-conf.json --no-sandbox &
          echo "E2E_BASE_URL=http://localhost:7860/" >> $GITHUB_ENV
        env:
          CI: true

      - name: Wait for server
        run: sleep 10

      - name: Run E2E tests
        run: npx ng e2e
        env:
          CHROME_BIN: /usr/bin/chromium

      - name: Check test results
        if: always()
        run: |
          echo "Test results summary:"
          if [ -d "coverage" ]; then
            echo "Coverage report generated. Listing files:"
            ls -la coverage
            if [ -f "coverage/lcov.info" ]; then
              echo "Coverage summary:"
              grep -E '^(SF|LF|LH)' coverage/lcov.info || echo "No coverage data"
            fi
          else
            echo "No coverage report generated."
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: frontend/coverage
          retention-days: 7
