name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build backend
        run: mvn clean package

      - name: Run backend tests
        run: mvn test

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Установка Puppeteer и Protractor
        run: |
          npm install -g protractor
          npm install puppeteer
          npx webdriver-manager update --gecko=false --standalone=false
        env:
          PUPPETEER_SKIP_DOWNLOAD: 'false'

      - name: Установить CHROME_BIN из Puppeteer
        run: |
          CHROME_BIN=$(node -e "console.log(require('puppeteer').executablePath())")
          echo "CHROME_BIN=$CHROME_BIN" >> $GITHUB_ENV

      - name: Debug Chromium и ChromeDriver
        run: |
          echo "CHROME_BIN: $CHROME_BIN"
          $CHROME_BIN --version || echo "Chromium not executable"
          node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_* --version || echo "ChromeDriver not found"

      - name: List test files
        run: |
          echo "Unit test files:"
          find src/app -name "*.spec.ts"
          echo "E2E test files:"
          find e2e/src -name "*.e2e-spec.ts"

      - name: Debug Karma и Angular
        run: |
          npx karma --version
          npx ng version
          protractor --version

      - name: Build project
        run: npx ng build

      - name: Run unit tests
        run: npx ng test --browsers=ChromeHeadless --watch=false
        env:
          CHROME_BIN: ${{ env.CHROME_BIN }}

      - name: Kill existing processes on port 7860
        run: fuser -k 7860/tcp || true

      - name: Kill existing processes on port 8080
        run: fuser -k 8080/tcp || true

      - name: Start backend
        run: |
          cd ../backend
          mvn spring-boot:run &
          sleep 10

      - name: Debug backend port
        run: lsof -i :8080 || echo "Port 8080 is free"

      - name: Start server for E2E tests
        run: |
          npx ng serve --port 7860 --proxy-config proxy-conf.json &
          echo "E2E_BASE_URL=http://localhost:7860/" >> $GITHUB_ENV
        env:
          CI: true

      - name: Wait for server
        run: sleep 10

      - name: Run E2E tests
        run: npx ng e2e
        env:
          CHROME_BIN: ${{ env.CHROME_BIN }}

      - name: Check test results
        if: always()
        run: |
          echo "Test results summary:"
          if [ -d "coverage" ]; then
            echo "Coverage report generated. Listing files:"
            ls -la coverage
            if [ -f "coverage/lcov.info" ]; then
              echo "Coverage summary:"
              cat coverage/lcov.info | grep -E '^(SF|LF|LH)' || echo "No coverage data"
            fi
          else
            echo "No coverage report generated."

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: frontend/coverage
          retention-days: 7
