name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build backend
        run: mvn clean package

      - name: Run backend tests
        run: mvn test

  frontend:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies for Chromium and tools
        run: |
          apt-get update
          apt-get install -y libnss3 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libgbm1 wget gdebi-core

      - name: Download Chromium and ChromeDriver debs
        run: |
          wget http://ftp.ru.debian.org/debian/pool/main/c/chromium/chromium_136.0.7103.113-1_amd64.deb
          wget http://ftp.ru.debian.org/debian/pool/main/c/chromium/chromium-driver_136.0.7103.113-1_amd64.deb

      - name: Install Chromium and ChromeDriver
        run: |
          gdebi --non-interactive chromium_136.0.7103.113-1_amd64.deb
          gdebi --non-interactive chromium-driver_136.0.7103.113-1_amd64.deb
          echo "CHROME_BIN=/usr/bin/chromium" >> $GITHUB_ENV

      - name: Debug Chromium installation
        run: |
          which chromium || echo "Chromium not found"
          chromium --version || echo "Chromium version check failed"
          which chromedriver || echo "ChromeDriver not found"
          chromedriver --version || echo "ChromeDriver version check failed"

      - name: Install npm dependencies
        run: npm ci

      - name: Install Protractor globally
        run: npm install -g protractor

      - name: Copy ChromeDriver to Protractor webdriver-manager folder
        run: |
          mkdir -p node_modules/protractor/node_modules/webdriver-manager/selenium
          cp $(which chromedriver) node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_136.0.7103.113
          chmod +x node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_136.0.7103.113

      - name: Debug ChromeDriver
        run: |
          ls -l node_modules/protractor/node_modules/webdriver-manager/selenium
          node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_136.0.7103.113 --version

      - name: List test files
        run: |
          echo "Unit test files:"
          find src/app -name "*.spec.ts"
          echo "E2E test files:"
          find e2e/src -name "*.e2e-spec.ts"

      - name: Build Angular project
        run: npx ng build

      - name: Run unit tests
        run: npx ng test --browsers=ChromiumHeadless --watch=false
        env:
          CHROME_BIN: /usr/bin/chromium
          CI: true

      - name: Kill processes on port 7860
        run: fuser -k 7860/tcp || true

      - name: Kill processes on port 8080
        run: fuser -k 8080/tcp || true

      - name: Start backend Spring Boot app
        run: |
          cd ../backend
          mvn spring-boot:run &
          sleep 10

      - name: Start Angular dev server for E2E tests
        run: |
          npx ng serve --port 7860 --proxy-config proxy-conf.json &
          echo "E2E_BASE_URL=http://localhost:7860/" >> $GITHUB_ENV
        env:
          CI: true

      - name: Wait for Angular server to start
        run: sleep 10

      - name: Run E2E tests
        run: npx ng e2e
        env:
          CHROME_BIN: /usr/bin/chromium

      - name: Check test results
        if: always()
        run: |
          echo "Test results summary:"
          if [ -d "coverage" ]; then
            echo "Coverage report generated. Listing files:"
            ls -la coverage
            if [ -f "coverage/lcov.info" ]; then
              grep -E '^(SF|LF|LH)' coverage/lcov.info || echo "No coverage data"
            fi
          else
            echo "No coverage report generated."
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: frontend/coverage
          retention-days: 7
