name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Build backend
        run: mvn clean package
      - name: Run backend tests
        run: mvn test

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: frontend/package.json
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install ChromeHeadless
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV
      - name: Debug Chrome version
        run: google-chrome --version
      - name: Install dependencies
        run: npm ci
      - name: List test files
        run: |
          echo "Unit test files:"
          find src/app -name "*.spec.ts"
          echo "E2E test files:"
          find e2e/src -name "*.e2e-spec.ts"
      - name: Debug Karma and Chrome
        run: |
          npx karma start --version
          google-chrome --version
          npx ng version
          protractor --version
      - name: Build project
        run: npx ng build
      - name: Run unit tests
        run: npx ng test --browsers=ChromeHeadless --watch=false
        env:
          CHROME_BIN: /usr/bin/google-chrome
      - name: Start server for E2E tests
        run: npx ng serve --proxy-config proxy-conf.json &
        env:
          CI: true
      - name: Check test results
        if: always()
        run: |
          echo "Test results summary:"
          if [ -d "coverage" ]; then
            echo "Coverage report generated. Listing files:"
            ls -la coverage
            if [ -f "coverage/lcov.info" ]; then
              echo "Coverage summary:"
              cat coverage/lcov.info | grep -E '^(SF|LF|LH)' || echo "No coverage data"
            fi
          else
            echo "No coverage report generated."
          fi
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: frontend/coverage
          retention-days: 7
