name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build backend
        run: mvn clean package

      - name: Run backend tests
        run: mvn test

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Chromium + ChromeDriver (v85)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gdebi-core libnss3 libxss1 libasound2t64 libatk-bridge2.0-0 libgtk-3-0 libgbm1

          wget http://security.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-chromedriver_85.0.4183.83-0ubuntu2.22.04.1_amd64.deb
          wget http://security.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-browser_85.0.4183.83-0ubuntu2.22.04.1_amd64.deb

          sudo gdebi --non-interactive chromium-browser_85.0.4183.83-0ubuntu2.22.04.1_amd64.deb
          sudo gdebi --non-interactive chromium-chromedriver_85.0.4183.83-0ubuntu2.22.04.1_amd64.deb

          echo "CHROME_BIN=/usr/lib/chromium-browser/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=/usr/lib/chromium-browser/chromedriver" >> $GITHUB_ENV

      - name: Debug Chrome install
        run: |
          $CHROME_BIN --version || echo "Chromium version check failed"
          $CHROMEDRIVER_BIN --version || echo "ChromeDriver version check failed"

      - name: Install dependencies
        run: npm ci

      - name: Install Protractor
        run: npm install -g protractor

      - name: Copy ChromeDriver to Protractor
        run: |
          mkdir -p node_modules/protractor/node_modules/webdriver-manager/selenium
          cp $CHROMEDRIVER_BIN node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_85.0.4183.83
          chmod +x node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_85.0.4183.83

      - name: Build project
        run: npx ng build

      - name: Run unit tests
        run: npx ng test --browsers=ChromiumHeadless --watch=false
        env:
          CHROME_BIN: ${{ env.CHROME_BIN }}
          CI: true

      - name: Kill existing backend ports
        run: |
          fuser -k 7860/tcp || true
          fuser -k 8080/tcp || true

      - name: Start backend
        run: |
          cd ../backend
          mvn spring-boot:run &
          sleep 10

      - name: Start frontend dev server
        run: |
          npx ng serve --port 7860 --proxy-config proxy-conf.json &
          echo "E2E_BASE_URL=http://localhost:7860/" >> $GITHUB_ENV
        env:
          CI: true

      - name: Wait for frontend
        run: sleep 10

      - name: Run E2E tests
        run: npx ng e2e
        env:
          CHROME_BIN: ${{ env.CHROME_BIN }}

      - name: Check test results
        if: always()
        run: |
          echo "Test results summary:"
          if [ -d "coverage" ]; then
            ls -la coverage
            if [ -f "coverage/lcov.info" ]; then
              grep -E '^(SF|LF|LH)' coverage/lcov.info || echo "No coverage data"
            fi
          else
            echo "No coverage report generated."
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: frontend/coverage
          retention-days: 7
